@startuml MultipleChoiceQuestion Diagram

left to right direction

actor Felhasználó

package "Általános elem" {
    usecase "Elem létrehozása" as CreateElement #E9BABA
    usecase "Elem szerkesztése" as EditElement #D2E9BA
    usecase "Elem megtekintése" as ViewElement #BAE9E9
    usecase "Elem törlése" as DeleteElement #D1BAE9
}

package "Feleletválasztós kérdés" {
    usecase "Feleletválasztós kérdés létrehozása" as CreateMultipleChoiceQuestion #E9BABA
    usecase "Feleletválasztós kérdés szerkesztése" as EditMultipleChoiceQuestion #D2E9BA
    usecase "Feleletválasztós kérdés megtekintése" as ViewMultipleChoiceQuestion #BAE9E9
    usecase "Feleletválasztós kérdés törlése" as DeleteMultipleChoiceQuestion #D1BAE9

    CreateMultipleChoiceQuestion -[#E9BABA]|> CreateElement
    EditMultipleChoiceQuestion -[#D2E9BA]|> EditElement
    ViewMultipleChoiceQuestion -[#BAE9E9]|> ViewElement
    DeleteMultipleChoiceQuestion -[#D1BAE9]|> DeleteElement
}

Felhasználó -[#E9BABA]-> CreateMultipleChoiceQuestion
Felhasználó -[#D2E9BA]-> EditMultipleChoiceQuestion
Felhasználó -[#BAE9E9]-> ViewMultipleChoiceQuestion
Felhasználó -[#D1BAE9]-> DeleteMultipleChoiceQuestion

@enduml
