name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: windows-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install winget
        uses: Cyberboss/install-winget@v1
      - name: Compile latex
        run: |
          winget install --accept-package-agreements --accept-source-agreements MiKTeX.MiKTeX 
          cd DiplomatervSablon_LaTeX_v1
          pdflatex thesis.tex || true
      - name: Upload PDF file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: thesis
          path: DiplomatervSablon_LaTeX_v1/thesis.pdf