name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile latex
        run: | 
          cd DiplomatervSablon_LaTeX_v1
          make compile_xelatex  || echo 'a' > /dev/null  
      - name: Upload PDF file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: thesis
          path: DiplomatervSablon_LaTeX_v1/thesis.pdf